"use client";
import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en"); // Default to English

  const translations = {
    en: {
      welcome: "Welcome to Pronoun 🌈",
      discover:
        "Discover your identity with love and pride. Let’s create your personalized badge!",
      signup: "Sign Up",
      login: "Log In",
      welcomeBack: "Welcome back, {name}! Ready to explore?",
      continueQuestions: "Continue to Questions",
      viewProfile: "View Profile",
      signOut: "Sign Out",
      oops: "Oops! Something Went Wrong 😔",
      authError: "Failed to load authentication state. Please try again.",
      goToLogin: "Go to Login",
      loading: "Loading...",
      join: "Join Pronoun 🌟",
      createAccount: "Create an account to start your journey!",
      email: "Email",
      password: "Password",
      signUp: "Sign Up",
      signInWithGoogle: "Sign up with Google",
      alreadyHaveAccount: "Already have an account?",
      logInLink: "Log In",
      logInTitle: "Log In to Pronoun 💖",
      continueJourney: "Sign in to continue your journey with us!",
      signIn: "Log In",
      signInWithGoogleLogin: "Sign in with Google",
      dontHaveAccount: "Don’t have an account?",
      signUpLink: "Sign Up",
      unlockBadge: "Unlock Your Pronoun Badge 🏳️‍🌈",
      paywallText:
        "You’re one step away from your personalized badge! Complete a one-time payment of <strong>5 EUR</strong> to view your badge and access premium features.",
      fakePaymentNote: '(This is a demo paywall. Click "Pay Now" to proceed.)',
      payNow: "Pay 5 EUR",
      yourBadge: "Your Pronoun Badge 🌟",
      badgeDescription: "Here’s your personalized badge based on your answers!",
      yourProfile: "Your Profile",
      yourInfo: "Your Information",
      emailLabel: "Email:",
      identityLabel: "Identity:",
      pronounsLabel: "Pronouns:",
      accountStatus: "Account Status:",
      premiumMember: "Premium Member",
      freeAccount: "Free Account",
      badgePreview: "Your Badge",
      badgePreviewDesc: "View your personalized pronoun badge.",
      viewBadge: "View Your Badge",
      upgrade: "Upgrade to See Your Badge",
      completeQuestions: "Complete Questions",
      backToHome: "Back to Home",
      languageToggle: "Switch to Deutsch",
      questionsTitle: "Explore Your Sexuality 💖",
      questionsSubtitle:
        "Answer these questions to discover your identity. Your responses are private.",
      attractionQuestion: "Who are you attracted to?",
      attractionSelect: "Select...",
      attractionMen: "Men",
      attractionWomen: "Women",
      attractionNonbinary: "Non-binary people",
      attractionAll: "All genders",
      attractionNone: "No one",
      attractionUnsure: "Unsure",
      intensityQuestion: "How strong is your attraction?",
      intensitySelect: "Select...",
      intensityStrong: "Very strong",
      intensityModerate: "Moderate",
      intensityWeak: "Weak",
      intensityNone: "None",
      intensityUnsure: "Unsure",
      relationshipQuestion: "What relationship structure feels right?",
      relationshipSelect: "Select...",
      relationshipMonogamous: "Monogamous",
      relationshipPolyamorous: "Open/Polyamorous",
      relationshipNone: "No relationships",
      relationshipUnsure: "Unsure",
      cultureQuestion: "How much does culture/religion influence you?",
      cultureSelect: "Select...",
      cultureALot: "A lot",
      cultureSome: "Some",
      cultureNotMuch: "Not much",
      cultureNotAtAll: "Not at all",
      cultureUnsure: "Unsure",
      identityQuestion: "How do you identify your sexuality?",
      identitySelect: "Select...",
      identityHeterosexual: "Heterosexual",
      identityHomosexual: "Homosexual",
      identityBisexual: "Bisexual",
      identityAsexual: "Asexual",
      identityPansexual: "Pansexual",
      identityQueer: "Queer",
      identityOther: "Other",
      identityUnsure: "Unsure",
      submit: "Submit",
      errorAllQuestions: "Please answer all questions",
      errorNotAuthenticated: "User not authenticated",
      notSpecified: "Not specified",
    },
    de: {
      welcome: "Willkommen bei Pronoun 🌈",
      discover:
        "Entdecke deine Identität mit Liebe und Stolz. Lass uns dein personalisiertes Abzeichen erstellen!",
      signup: "Registrieren",
      login: "Anmelden",
      welcomeBack: "Willkommen zurück, {name}! Bereit zu erkunden?",
      continueQuestions: "Zu den Fragen weiter",
      viewProfile: "Profil ansehen",
      signOut: "Abmelden",
      oops: "Hoppla! Etwas ist schiefgelaufen 😔",
      authError:
        "Fehler beim Laden des Authentifizierungsstatus. Bitte versuche es erneut.",
      goToLogin: "Zur Anmeldung",
      loading: "Laden...",
      join: "Tritt Pronoun bei 🌟",
      createAccount: "Erstelle ein Konto, um deine Reise zu beginnen!",
      email: "E-Mail",
      password: "Passwort",
      signUp: "Registrieren",
      signInWithGoogle: "Mit Google registrieren",
      alreadyHaveAccount: "Hast du bereits ein Konto?",
      logInLink: "Anmelden",
      logInTitle: "Anmelden bei Pronoun 💖",
      continueJourney: "Melde dich an, um deine Reise mit uns fortzusetzen!",
      signIn: "Anmelden",
      signInWithGoogleLogin: "Mit Google anmelden",
      dontHaveAccount: "Hast du noch kein Konto?",
      signUpLink: "Registrieren",
      unlockBadge: "Entsperre dein Pronomen-Abzeichen 🏳️‍🌈",
      paywallText:
        "Du bist nur einen Schritt von deinem personalisierten Abzeichen entfernt! Zahle einmalig <strong>5 EUR</strong>, um dein Abzeichen zu sehen und Premium-Funktionen zu nutzen.",
      fakePaymentNote:
        '(Dies ist eine Demo-Zahlwand. Klicke auf "Jetzt zahlen", um fortzufahren.)',
      payNow: "5 EUR zahlen",
      yourBadge: "Dein Pronomen-Abzeichen 🌟",
      badgeDescription:
        "Hier ist dein personalisiertes Abzeichen basierend auf deinen Antworten!",
      yourProfile: "Dein Profil",
      yourInfo: "Deine Informationen",
      emailLabel: "E-Mail:",
      identityLabel: "Identität:",
      pronounsLabel: "Pronomen:",
      accountStatus: "Kontostatus:",
      premiumMember: "Premium-Mitglied",
      freeAccount: "Kostenloses Konto",
      badgePreview: "Dein Abzeichen",
      badgePreviewDesc: "Sieh dir dein personalisiertes Pronomen-Abzeichen an.",
      viewBadge: "Abzeichen ansehen",
      upgrade: "Upgrade, um dein Abzeichen zu sehen",
      completeQuestions: "Fragen beantworten",
      backToHome: "Zurück zur Startseite",
      languageToggle: "Auf Englisch wechseln",
      questionsTitle: "Erkunde deine Sexualität 💖",
      questionsSubtitle:
        "Beantworte diese Fragen, um deine Identität zu entdecken. Deine Antworten sind privat.",
      attractionQuestion: "Zu wem fühlst du dich hingezogen?",
      attractionSelect: "Auswählen...",
      attractionMen: "Männer",
      attractionWomen: "Frauen",
      attractionNonbinary: "Nicht-binäre Personen",
      attractionAll: "Alle Geschlechter",
      attractionNone: "Niemand",
      attractionUnsure: "Unsicher",
      intensityQuestion: "Wie stark ist deine Anziehung?",
      intensitySelect: "Auswählen...",
      intensityStrong: "Sehr stark",
      intensityModerate: "Moderat",
      intensityWeak: "Schwach",
      intensityNone: "Keine",
      intensityUnsure: "Unsicher",
      relationshipQuestion: "Welche Beziehungsstruktur fühlt sich richtig an?",
      relationshipSelect: "Auswählen...",
      relationshipMonogamous: "Monogam",
      relationshipPolyamorous: "Offen/Polyamor",
      relationshipNone: "Keine Beziehungen",
      relationshipUnsure: "Unsicher",
      cultureQuestion: "Wie stark beeinflusst dich Kultur/Religion?",
      cultureSelect: "Auswählen...",
      cultureALot: "Sehr",
      cultureSome: "Etwas",
      cultureNotMuch: "Wenig",
      cultureNotAtAll: "Gar nicht",
      cultureUnsure: "Unsicher",
      identityQuestion: "Wie identifizierst du deine Sexualität?",
      identitySelect: "Auswählen...",
      identityHeterosexual: "Heterosexuell",
      identityHomosexual: "Homosexuell",
      identityBisexual: "Bisexuell",
      identityAsexual: "Asexuell",
      identityPansexual: "Pansexuell",
      identityQueer: "Queer",
      identityOther: "Andere",
      identityUnsure: "Unsicher",
      submit: "Absenden",
      errorAllQuestions: "Bitte beantworte alle Fragen",
      errorNotAuthenticated: "Benutzer nicht authentifiziert",
      notSpecified: "Nicht angegeben",
    },
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "de" : "en"));
  };

  return (
    <LanguageContext.Provider
      value={{ language, toggleLanguage, translations }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
